project:
  type: book
  post-render: bash script/post_render.sh

book:
  title: František Ignác Antonín Tůma
  subtitle: A thematic catalogue of his works (TumW)
  author: Wolfgang Esser-Skala
  date: today
  date-format: "YYYY-MM-DD [(v0.15.0.9000)]"
  site-url: https://www.frantisek-tuma.at
  sidebar:
    title: František Ignác Antonín Tůma. A thematic catalogue of his works (TumW)
  chapters:
    - index.qmd
    - metadata.qmd
    - groups/overview.qmd
    - part: "Vocal music"
      chapters:
        - groups/masses.qmd
        - groups/requiems.qmd
        - groups/liturgical_works.qmd
        - groups/vespers.qmd
        - groups/marian_antiphons.qmd
        - groups/sequences.qmd
        - groups/litanies.qmd
        - groups/misc_vocal.qmd
    - part: "Instrumental music"
      chapters:
        - groups/sonatas.qmd
        - groups/sinfonias.qmd
        - groups/partitas.qmd
        - groups/misc_instrumental.qmd
    - bibliography.qmd
    - part: "Appendix"
      chapters:
        - concordances.qmd
        - inventories.qmd
        - prints.qmd
        - indices.qmd
        - abbreviations.qmd
    - part: "Technical documentation"
      chapters:
        - guidelines.qmd
        - changelog.qmd
  page-navigation: false
  favicon: images/favicon.png

bibliography:
 - editions.bib
 - inventories.bib
 - references.bib
csl: "apa-6th-edition.csl"

format:
  html:
    toc-depth: 2
    theme:
      light: [flatly, styling.scss]
      dark: [darkly, styling.scss, styling-dark.scss]
include-after-body:
  text: |
    <script type="application/javascript" src="/light-dark.js"></script>
